parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
      rix_vimeo:
         class: RIX\CoreBundle\Service\Vimeo\Vimeo
